# Generated by Django 3.0.5 on 2020-08-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100, verbose_name='realname')),
                ('tx', models.CharField(max_length=100, verbose_name='tx')),
                ('activityref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberref', to='fullthrottleapp.ActivityPeriods')),
            ],
        ),
    ]
