# Generated by Django 3.0.5 on 2020-08-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullthrottleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='activityref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberref', to='fullthrottleapp.ActivityPeriods'),
        ),
    ]
