# Generated by Django 3.0.5 on 2020-08-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullthrottleapp', '0002_auto_20200813_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='activityref',
            new_name='activity_periods',
        ),
    ]
